name: wmm ci pipeline

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [ '3.9', '3.10', '3.11', '3.12' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: |
        python -m unittest tests/Test_wmm.py
        python tests/test_vec.py

    - name: Run scientific accuracy tests
      run: |
        python tests/SystemTest.py
        

    - name: Upload Test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: tests/diff_results.csv